# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAA8LcwGiTmPOKB5VQ_1KZUOatkWzSC6

Upload the dataset into Colab
"""

import pandas as pd
df = pd.read_csv('/content/adult.csv')
df.head()

"""Clean the Adult dataset"""

adult_column_names = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

# If your CSV has NO header row (UCI original), keep header=None
df = pd.read_csv(
    '/content/adult.csv',
    header=None,
    names=adult_column_names,
    na_values=["?", " ?"]   # treat ? as missing
)

print("Shape:", df.shape)
df.head()

"""Basic info & whitespace cleanup"""

print("\nData types:")
print(df.dtypes)

print("\nInfo:")
print(df.info())

# Strip whitespace from string columns
str_cols = df.select_dtypes(include=["object"]).columns
df[str_cols] = df[str_cols].apply(lambda col: col.str.strip())

# Save cleaned version (optional, for your GitHub)
df.to_csv("adult_cleaned.csv", index=False)

"""# Task --Completeness / missing values
Analyze missing values in the DataFrame `df` by calculating the number and percentage of missing values for each column and display a sorted summary.

## Analyze Missing Values

### Subtask:
Calculate the number and percentage of missing values for each column in the DataFrame `df` and display a sorted summary.

## Summary:

### Data Analysis Key Findings
*   The analysis aimed to identify all columns within the DataFrame `df` that contain missing values.
*   For each column identified with missing data, the exact count and the corresponding percentage of missing values were calculated.
*   A summary was generated, presenting these findings in a sorted order, typically by the percentage of missing values to highlight columns requiring immediate attention.

### Insights or Next Steps
*   Based on the identified columns and their respective percentages of missing values, a strategy for data imputation or deletion should be developed.
*   Further investigation is needed to understand the underlying reasons for the missing data in critical columns, which could inform data collection processes or highlight data quality issues.
"""

missing_counts = df.isna().sum()
missing_pct = (missing_counts / len(df)) * 100

missing_summary = (
    pd.DataFrame({
        "missing_count": missing_counts,
        "missing_pct": missing_pct.round(2)
    })
    .sort_values("missing_pct", ascending=False)
)

print("Missing values summary:")
missing_summary

"""Plot missing % per column:"""

import seaborn as sns
import os
import matplotlib.pyplot as plt

# Create directories if they don't exist
os.makedirs('results', exist_ok=True)
os.makedirs('figures', exist_ok=True)

missing_summary.to_csv("results/missing_summary.csv")

plt.figure()
sns.barplot(
    x=missing_summary.index,
    y="missing_pct",
    data=missing_summary.reset_index()
)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Missing %")
plt.title("Missing Values by Column")
plt.tight_layout()
plt.savefig("figures/missing_by_column.png", dpi=150)
plt.show()

"""Results:

The analysis of missing values revealed that the 'occupation' column has the highest percentage of missing values at 5.66%, followed closely by 'workclass' at 5.64%, and then 'native_country' at 1.79%. All other columns have no missing values. This information is summarized in the missing_summary DataFrame and visualized in the bar plot missing_by_column.png.

Class distribution (income) & class imbalance
"""

income_counts = df["income"].value_counts()
income_pct = (income_counts / len(df)) * 100

income_dist = pd.DataFrame({
    "count": income_counts,
    "pct": income_pct.round(2)
})

print("Income distribution:")
income_dist

plt.figure()
sns.barplot(
    x=income_dist.index,
    y="pct",
    data=income_dist.reset_index()
)
plt.ylabel("Percentage of Records")
plt.title("Income Class Distribution")
plt.tight_layout()
plt.savefig("figures/income_class_distribution.png", dpi=150)
plt.show()

print("Income distribution:")
print(income_dist)

"""## Income Class Distribution Results:

The analysis of the 'income' column revealed the following distribution:

*   **`<=50K`**: 24,720 records, accounting for **75.92%** of the dataset.
*   **`>50K`**: 7,841 records, accounting for **24.08%** of the dataset.
*   There was also a single record labeled 'Income' (0.00%), which appears to be an anomaly or a remnant from a header entry.

This distribution highlights a significant class imbalance, with the majority of individuals in the dataset earning `<=50K`.

Sampling bias: gender & race distribution
"""

print("Sex distribution (%):")
print(df["sex"].value_counts(normalize=True).mul(100).round(2))

print("\nRace distribution (%):")
print(df["race"].value_counts(normalize=True).mul(100).round(2))

sex_dist = df["sex"].value_counts(normalize=True).mul(100).reset_index()
sex_dist.columns = ["sex", "pct"]

plt.figure()
sns.barplot(x="sex", y="pct", data=sex_dist)
plt.ylabel("Percentage of Records")
plt.title("Gender Distribution (Sampling Bias Check)")
plt.tight_layout()
plt.savefig("figures/gender_distribution.png", dpi=150)
plt.show()

race_dist = df["race"].value_counts(normalize=True).mul(100).reset_index()
race_dist.columns = ["race", "pct"]

plt.figure()
sns.barplot(x="race", y="pct", data=race_dist)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Percentage of Records")
plt.title("Race Distribution (Sampling Bias Check)")
plt.tight_layout()
plt.savefig("figures/race_distribution.png", dpi=150)
plt.show()

"""## Summary: Gender and Race Distribution

### Data Analysis Key Findings

#### Gender Distribution:
*   The dataset shows a significant imbalance in gender representation:
    *   **Male**: Approximately 66.92% of the records.
    *   **Female**: Approximately 33.08% of the records.
    *   There is also an anomaly of one record labeled 'Sex', likely a header remnant, similar to the 'Income' anomaly.

#### Race Distribution:
*   The race distribution also exhibits a strong imbalance:
    *   **White**: Dominates the dataset with approximately 85.42% of the records.
    *   **Black**: Accounts for approximately 9.59%.
    *   **Asian-Pac-Islander**: Accounts for approximately 3.19%.
    *   **Amer-Indian-Eskimo**: Accounts for approximately 0.96%.
    *   **Other**: Accounts for approximately 0.83%.
    *   Similar to gender and income, there's one anomalous record labeled 'Race'.

### Insights and Potential Biases
*   **Gender Bias**: The dataset is heavily skewed towards male individuals, who constitute nearly two-thirds of the records. This significant overrepresentation of males could introduce sampling bias and potentially affect the generalizability of any models trained on this data, particularly if gender is a predictive feature for income.
*   **Racial Bias**: The dataset is overwhelmingly composed of individuals identified as 'White'. This extreme overrepresentation could lead to models that perform very well for the majority group but poorly for underrepresented racial groups. Any insights or predictions derived from this dataset regarding income, workclass, or other attributes should be interpreted with caution, acknowledging the potential for racial bias and lack of generalizability to more diverse populations.
*   The presence of single anomalous records like 'Sex', 'Race', and 'Income' indicates that the initial row containing column headers was incorrectly parsed as data, which needs to be addressed in the data cleaning process to prevent erroneous calculations or analyses.

Fairness-related: income by gender & race
"""

# Income by gender
gender_income = (
    df.groupby("sex")["income"]
      .value_counts(normalize=True)
      .mul(100)
      .rename("pct")
      .reset_index()
)

print("Income distribution by gender (%):")
gender_income

#plot
plt.figure()
sns.barplot(
    x="sex",
    y="pct",
    hue="income",
    data=gender_income
)
plt.ylabel("Percentage within Gender")
plt.title("Income Distribution by Gender")
plt.legend(title="Income")
plt.tight_layout()
plt.savefig("figures/income_by_gender.png", dpi=150)
plt.show()

#NOW BY RACE
race_income = (
    df.groupby("race")["income"]
      .value_counts(normalize=True)
      .mul(100)
      .rename("pct")
      .reset_index()
)

print("Income distribution by race (%):")
race_income

#plot
plt.figure()
sns.barplot(
    x="race",
    y="pct",
    hue="income",
    data=race_income
)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Percentage within Race")
plt.title("Income Distribution by Race")
plt.legend(title="Income")
plt.tight_layout()
plt.savefig("figures/income_by_race.png", dpi=150)
plt.show()

"""## Summary: Income Distribution by Gender and Race

### Data Analysis Key Findings

#### Income Distribution by Gender:
*   **Females**: A significant majority, approximately **89.05%**, earn `k`. Only about **10.95%** of females earn `>50K`.
*   **Males**: A lower proportion, approximately **69.43%**, earn `k`, while a much higher proportion, about **30.57%**, earn `>50K`.
*   There is an anomalous entry where `sex` is 'Sex' and `income` is 'Income', representing 100% (likely a header row artifact).

#### Income Distribution by Race:
*   **White**: Approximately **74.41%** earn `k`, and about **25.59%** earn `>50K`.
*   **Asian-Pac-Islander**: Approximately **73.44%** earn `k`, and about **26.56%** earn `>50K`.
*   **Black**: A high proportion, approximately **87.61%**, earn `k`, with only about **12.39%** earning `>50K`.
*   **Amer-Indian-Eskimo**: Approximately **88.42%** earn `k`, and about **11.58%** earn `>50K`.
*   **Other**: The highest proportion, approximately **90.77%**, earn `k`, and only about **9.23%** earn `>50K`.
*   There is an anomalous entry where `race` is 'Race' and `income` is 'Income', representing 100% (likely a header row artifact).

### Significant Disparities and Patterns:
*   **Gender Disparity**: There is a substantial disparity in income distribution between genders. Males are approximately three times more likely to earn `>50K` than females (30.57% vs. 10.95%). This suggests a significant gender pay gap or occupational segregation within the dataset.
*   **Racial Disparity**: Significant disparities also exist across racial groups. White and Asian-Pac-Islander individuals show a considerably higher proportion of individuals earning `>50K` compared to Black, Amer-Indian-Eskimo, and Other racial groups. Black, Amer-Indian-Eskimo, and Other groups have less than half the proportion of `>50K` earners compared to White and Asian-Pac-Islander groups.
*   **Advantaged Groups**: Based on the proportion of `>50K` earners, Males, White, and Asian-Pac-Islander individuals appear to be relatively advantaged in this dataset.
*   **Disadvantaged Groups**: Females, Black, Amer-Indian-Eskimo, and Other racial groups appear to be significantly disadvantaged in terms of higher income earners in this dataset.

### Anomalies Noted:
*   The presence of single anomalous records like 'Sex' in `gender_income` and 'Race' in `race_income` with 'Income' as the category and 100% proportion confirms that the original header row was mistakenly included as a data entry during data loading, and this has propagated through the grouping operations. These should be excluded from future analysis to ensure data integrity.

Feature quality / validity (outliers & distributions)
"""

# Drop the first row which contains the original header as data
df = df.iloc[1:].copy()

# Convert 'age' and 'hours_per_week' to numeric. Coerce errors will turn invalid parsing into NaN.
df["age"] = pd.to_numeric(df["age"], errors='coerce')
df["hours_per_week"] = pd.to_numeric(df["hours_per_week"], errors='coerce')

print("Age describe():")
print(df["age"].describe())

plt.figure()
sns.histplot(df["age"], bins=30, kde=False)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.tight_layout()
plt.savefig("figures/age_distribution.png", dpi=150)
plt.show()

print("\nHours per week describe():")
print(df["hours_per_week"].describe())

plt.figure()
sns.boxplot(x=df["hours_per_week"])
plt.title("Hours per Week – Outlier Check")
plt.tight_layout()
plt.savefig("figures/hours_per_week_boxplot.png", dpi=150)
plt.show()

# Check extreme hours/week > 80
outliers_hours = df[df["hours_per_week"] > 80]
print(f"\nRows with hours_per_week > 80: {len(outliers_hours)}")
outliers_hours[["age", "workclass", "occupation", "hours_per_week"]].head()

"""Here are the key findings from the analysis:

Age Distribution:

The age column now ranges from 17 to 90 years, with a mean of approximately 38.6 years. The median age is 37, and 75% of individuals are 48 or younger. A histogram showing the age distribution (figures/age_distribution.png) was also generated.
Hours per Week Distribution:

The hours_per_week column ranges from 1 to 99 hours, with a mean of about 40.4 hours. The most common working hours are around 40 per week. A boxplot (figures/hours_per_week_boxplot.png) was created to visualize its distribution and check for outliers.
Outliers in Hours per Week:

I found 208 rows where hours_per_week is greater than 80, suggesting a small number of individuals work exceptionally long hours. For example, some individuals work 90, 98, or 99 hours per week across various occupations and work classes. This might indicate valid intensive work schedules or potential data entry errors, which might warrant further investigation.

**Category** **consistency**
"""

for col in ["workclass", "education", "marital_status", "occupation", "relationship", "native_country"]:
    print(f"\nUnique values in {col}:")
    print(sorted(df[col].dropna().unique())[:30])  # first 30 unique values

"""Save high-level summary (for report & GitHub)"""

import pandas as pd
import numpy as np

missing_counts = df.isna().sum()
missing_pct = (missing_counts / len(df)) * 100

income_pct = df["income"].value_counts(normalize=True).mul(100)

sex_pct = df["sex"].value_counts(normalize=True).mul(100)

summary_notes = {
    "n_rows": len(df),
    "n_cols": df.shape[1],
    "columns_with_missing": int((missing_counts > 0).sum()),
    "max_missing_pct": float(missing_pct.max()),
    "income_>50K_pct": float(income_pct.get(">50K", np.nan)),
    "income_<=50K_pct": float(income_pct.get("<=50K", np.nan)),
    "male_pct": float(sex_pct.get("Male", np.nan)),
    "female_pct": float(sex_pct.get("Female", np.nan))
}

summary_df = pd.DataFrame(summary_notes, index=["value"]).T
summary_df

summary_df.to_csv("results/high_level_summary.csv")

from google.colab import files
files.download("results/high_level_summary.csv")